# Generated by Django 3.2.7 on 2021-09-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_code', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=120)),
                ('mobile_no', models.BigIntegerField()),
                ('salary', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
